baseURL = "https://lucasvandijk.nl/"
languageCode = "en-us"
title = '<span class="top">Lucas</span> <span class="bottom">van Dijk</span>'
copyright = "&copy; 2017 Lucas van Dijk"
theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
preserveTaxonomyNames = true
paginate = 10

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[outputs]
  home = [ "HTML", "CSS", "RSS" ]
  section = [ "HTML", "RSS" ]

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/readfiles/bfconfig/
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab.
  fractions = true  # `false` disables smart fractions (e.g. 5/12 formatted as a fraction).
  smartypants = true  # `false` disables all smart punctuation substitutions (e.g. smart quotes, dashes, fractions).


[permalinks]
  post = "/:year/:month/:title/"

[params]
  # Color theme.
  #   Choose from `default`, `ocean`, `forest`, `coffee`, or `dark`.
  color_theme = "lvd"

  # Font style.
  #   Choose from `default`, `classic`, or `playfair`.
  font = "lvd"

  name = "Lucas van Dijk"
  role = "PhD-candidate in bioinformatics"

  # Organizations/Affiliations.
  #   Separate multiple entries with a comma, using the form: `[ {name="Org1", url=""}, {name="Org2", url=""} ]`.
  organizations = [ 
    { name = "Broad Institute of MIT and Harvard", url = "https://broadinstitute.org" },
    { name = "Delft University of Technology", url = "https://tudelft.nl" }
  ]

  avatar = "portrait.jpg"
  gravatar = false
  email = "info@lucasvandijk.nl"
  keybase = "sh4wn"

  date_format = "Jan 2, 2006"

  highlight = true
  highlight_languages = ["python"]

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  sharing = true
  comment_count = true
  reading_time = true

  # Publication types.
  #   Used to categorize publications.
  #   The index of the publication type in the list is used as its unique numerical identifier.
  #   The numeric ID is used in a publication's frontmatter to categorize it.
  #   The language can be edited below.
  #   For multi-lingual sites, copy this block to each language section at the end of this file.
  publication_types = [
    'Uncategorized',  # 0
    'Conference proceedings',  # 1
    'Journal',  # 2
    'Work in progress',  # 3
    'Technical report',  # 4
    'Book',  # 5
    'Book chapter'  # 6
  ]

  # Configuration of talk pages.
  [params.talks]
    # Show talk time?
    time = true

  # Configuration of publication pages.
  [params.publications]
    # Date format (refer to Go's date format: http://fuckinggodateformat.com )
    #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
    date_format = "January, 2006"

  # Configuration of project pages.
  [params.projects]
    # List publications and talks related to the project?
    list_children = true

    # Publication list format.
    #   0 = Simple
    #   1 = Detailed
    #   2 = APA
    #   3 = MLA
    publication_format = 3

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:info@lucasvandijk.nl"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/lucasvandijk"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/lrvdijk"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "//linkedin.com/in/lrvandijk"

# Configure the English version of the website.
[languages.en]
  languageCode = "en-us"

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#top"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "#blog"
  weight = 2

# [[menu.main]]
#   name = "Publications"
#   url = "#publications_selected"
#   weight = 3

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 4
